// Practice problems: numeric answers checked within ±tol. `code` is a one-line JS check students can run.
export default [
 {type:{en:'EEE: waves',ta:'EEE: waves'},q:{en:'Indian mains electricity is 50 Hz. How many milliseconds does one full wave take?',ta:'இந்திய mains electricity 50 Hz. ஒரு முழு wave-க்கு எத்தனை milliseconds ஆகும்?'},unit:'ms',ans:20,tol:0.01,
  hint:{en:'50 waves every second, so one wave takes 1 ÷ 50 of a second.',ta:'ஒரு second-ல 50 waves, அதனால ஒரு wave-க்கு 1 ÷ 50 second.'},
  sol:{en:'1 ÷ 50 = 0.02 s = 20 ms.',ta:'1 ÷ 50 = 0.02 s = 20 ms.'},code:'1 / 50 * 1000'},
 {type:{en:'Health: heart rate',ta:'Health: heart rate'},q:{en:'A smartwatch sees 0.75 seconds between heartbeat peaks. What is the heart rate in beats per minute?',ta:'Smartwatch heartbeat peaks-க்கு நடுவுல 0.75 seconds பார்க்குது. நிமிஷத்துக்கு எத்தனை beats?'},unit:'bpm',ans:80,tol:0.5,
  hint:{en:'Beats per minute = 60 ÷ seconds per beat.',ta:'நிமிஷத்துக்கு beats = 60 ÷ ஒரு beat-க்கு seconds.'},sol:{en:'60 ÷ 0.75 = 80 bpm.',ta:'60 ÷ 0.75 = 80 bpm.'},code:'60 / 0.75'},
 {type:{en:'Waves: frequency',ta:'Waves: frequency'},q:{en:'A wave is y = 3 × sin(2π × 2 × t). How long is one full swing, in seconds?',ta:'ஒரு wave y = 3 × sin(2π × 2 × t). ஒரு முழு ஆட்டத்துக்கு எத்தனை seconds?'},unit:'s',ans:0.5,tol:0.001,
  hint:{en:'In y = A × sin(2π × f × t), f is the frequency. Period = 1 ÷ f.',ta:'y = A × sin(2π × f × t)-ல f தான் frequency. Period = 1 ÷ f.'},sol:{en:'f = 2 swings per second, so one swing takes 1 ÷ 2 = 0.5 s. (The 3 is the amplitude: it changes the height, not the speed.)',ta:'f = ஒரு second-ல 2 ஆட்டம், அதனால ஒரு ஆட்டம் 1 ÷ 2 = 0.5 s. (3 தான் amplitude: உயரத்தை மாத்தும், வேகத்தை இல்ல.)'},code:'1 / 2'},
 {type:{en:'EEE: peak voltage',ta:'EEE: peak voltage'},q:{en:'Home supply is 230 V effective. For a sine wave, peak = effective × √2. What is the peak voltage?',ta:'வீட்டு supply 230 V effective. Sine wave-க்கு peak = effective × √2. Peak voltage என்ன?'},unit:'V',ans:325.3,tol:0.5,
  hint:{en:'√2 ≈ 1.414.',ta:'√2 ≈ 1.414.'},sol:{en:'230 × 1.414 ≈ 325.3 V. That is why the wave swings to about ±325 V.',ta:'230 × 1.414 ≈ 325.3 V. அதனால தான் wave சுமார் ±325 V வரை ஆடுது.'},code:'230 * Math.SQRT2'},
 {type:{en:'Games: rain sway',ta:'Games: rain sway'},q:{en:'A raindrop starts at x0 = 200 with wind = 30 and phase = 0. Using x = x0 + wind × sin(2 × time + phase), where is it at time = π/4?',ta:'ஒரு raindrop x0 = 200-ல, wind = 30, phase = 0. x = x0 + wind × sin(2 × time + phase) use பண்ணா, time = π/4-ல அது எங்க இருக்கும்?'},unit:'',ans:230,tol:0.01,
  hint:{en:'2 × π/4 = π/2, and sin(π/2) = 1.',ta:'2 × π/4 = π/2, sin(π/2) = 1.'},sol:{en:'200 + 30 × sin(π/2) = 200 + 30 = 230: the drop has swayed fully to the right.',ta:'200 + 30 × sin(π/2) = 200 + 30 = 230: drop முழுசா வலது பக்கம் ஆடியிருக்கு.'},code:'200 + 30 * Math.sin(2 * Math.PI / 4 + 0)'},
 {type:{en:'Sound: a musical note',ta:'Sound: ஒரு musical note'},q:{en:'The musical note A vibrates at 440 Hz. How many milliseconds does one vibration take? (2 decimals)',ta:'Musical note A 440 Hz-ல அதிருது. ஒரு அதிர்வுக்கு எத்தனை milliseconds? (2 decimals)'},unit:'ms',ans:2.27,tol:0.01,
  hint:{en:'Period = 1 ÷ frequency, then × 1000 for milliseconds.',ta:'Period = 1 ÷ frequency, அப்புறம் milliseconds-க்கு × 1000.'},sol:{en:'1 ÷ 440 = 0.00227 s = 2.27 ms.',ta:'1 ÷ 440 = 0.00227 s = 2.27 ms.'},code:'1 / 440 * 1000'},
 {type:{en:'Data: seasons',ta:'Data: seasons'},q:{en:'The fitted model is T = 29 + 3.6 × cos(2π(m − 6.2) ÷ 12). What is the highest temperature it predicts?',ta:'Fit பண்ண model T = 29 + 3.6 × cos(2π(m − 6.2) ÷ 12). அது predict பண்ற அதிகபட்ச temperature என்ன?'},unit:'°C',ans:32.6,tol:0.05,
  hint:{en:'cos is at most 1.',ta:'cos அதிகபட்சம் 1.'},sol:{en:'Maximum when cos = 1: 29 + 3.6 = 32.6 °C, around month 6.2 (early June).',ta:'cos = 1 ஆகும் போது அதிகம்: 29 + 3.6 = 32.6 °C, சுமார் month 6.2 (June ஆரம்பம்).'},code:'29 + 3.6 * Math.cos(0)'}
];
