// Run: npm run seed
// Creates 1 admin + 5 students with notes, referral chain, scores,
// locations, notifications and feedback — so every Campus Arena
// screen has something to show on the very first demo.
require('dotenv').config();
const mongoose = require('mongoose');
const User = require('../models/User');
const Note = require('../models/Note');
const GameSession = require('../models/GameSession');
const Notification = require('../models/Notification');
const Feedback = require('../models/Feedback');

// Erode region. GeoJSON order: [LONGITUDE, LATITUDE] — lng first, always.
// 2 decimals ≈ 1.1 km, the same rounding the location controller applies.
const CAMPUS = [77.60, 11.30];

const run = async () => {
  await mongoose.connect(process.env.MONGO_URI);

  await Promise.all([
    User.deleteMany(),
    Note.deleteMany(),
    GameSession.deleteMany(),
    Notification.deleteMany(),
    Feedback.deleteMany(),
  ]);

  // ---- Build the indexes we declared in the schemas ----
  // Mongoose creates indexes lazily in the background, which means the FIRST
  // $geoNear or $text query after a fresh seed can fail with "no index found".
  // syncIndexes() forces them to exist now, and drops any that we removed.
  await Promise.all([
    User.syncIndexes(),
    GameSession.syncIndexes(),
    Notification.syncIndexes(),
    Feedback.syncIndexes(),
  ]);

  // ---------------------------------------------------------------
  // Users. Created in CHAIN ORDER, because each one needs the _id of
  // the person who invited them — you cannot reference a row that
  // does not exist yet. referralCode is generated by the model's hook.
  // ---------------------------------------------------------------
  const admin = await User.create({
    name: 'Admin',
    email: 'admin@demo.com',
    password: 'admin123',
    role: 'admin',
    bestScoreMs: 3950,
    location: { type: 'Point', coordinates: CAMPUS },
  });

  const mk = (name, extra) => ({
    name,
    email: `${name.toLowerCase()}@demo.com`,
    password: 'student123',
    ...extra,
  });

  // admin -> Arun -> Priya -> Divya, with Karthik also under Arun.
  // That gives $graphLookup three levels to walk from the admin:
  //   level 0: Arun      level 1: Priya, Karthik      level 2: Divya
  const arun = await User.create(
    mk('Arun', {
      referredBy: admin._id,
      bestScoreMs: 2680,
      profile: { year: 2, skills: ['react', 'node'] },
      location: { type: 'Point', coordinates: [77.62, 11.34] },   // ~5 km away
    })
  );
  const priya = await User.create(
    mk('Priya', {
      referredBy: arun._id,
      bestScoreMs: 3120,
      profile: { year: 2, skills: ['python'] },
      location: { type: 'Point', coordinates: [77.71, 11.26] },   // ~13 km
    })
  );
  const karthik = await User.create(
    mk('Karthik', {
      referredBy: arun._id,
      bestScoreMs: 2400,                                           // fastest = rank 1
      profile: { year: 2, skills: ['mongodb', 'express'] },
      location: { type: 'Point', coordinates: [77.55, 11.38] },   // ~10 km
    })
  );
  const divya = await User.create(
    mk('Divya', {
      referredBy: priya._id,
      bestScoreMs: 4850,
      profile: { year: 2, skills: ['java'] },
      location: { type: 'Point', coordinates: [77.68, 11.41] },   // ~14 km
    })
  );
  // Suresh joined on his own AND sits ~55 km away on purpose: he proves that
  // maxDistance really filters. If he ever shows up in "nearby", something broke.
  const suresh = await User.create(
    mk('Suresh', {
      bestScoreMs: 5200,
      profile: { year: 2, skills: ['react'] },
      location: { type: 'Point', coordinates: [78.10, 11.30] },
    })
  );

  const students = [arun, priya, karthik, divya, suresh];

  // ---- Notes (unchanged lesson: arrays + nested meta) ----
  const tags = ['dsa', 'placement', 'project', 'exam', 'mern'];
  const notes = [];
  students.forEach((s, i) => {
    for (let n = 0; n <= i; n++) {
      notes.push({
        user: s._id,
        title: `${s.name}'s note ${n + 1}`,
        body: 'Sample body',
        tags: [tags[n % tags.length], tags[(n + 1) % tags.length]],
        meta: { priority: ['low', 'medium', 'high'][n % 3], pinned: n === 0 },
      });
    }
  });
  await Note.create(notes);

  // ---- Two notifications waiting for Arun, so the bell has a badge on login ----
  await Notification.insertMany([
    {
      user: arun._id,
      type: 'BEAT_SCORE',
      message: 'Karthik beat your best score with 2400ms!',
    },
    {
      user: arun._id,
      type: 'NEW_REFERRAL',
      message: 'Priya joined using your referral link!',
    },
  ]);

  // ---- Feedback with searchable words, for the admin $text demo ----
  // Deliberately NOT from Arun: the 1-per-hour limit would then block the
  // very first thing you try in the demo.
  await Feedback.insertMany([
    { user: priya._id, rating: 5, message: 'The reaction game is awesome, I played it ten times in a row.' },
    { user: karthik._id, rating: 3, message: 'Good game but the slow wifi in the lab ruins my score.' },
    { user: divya._id, rating: 4, message: 'Leaderboard is motivating. Wish the game had more levels.' },
  ]);

  console.log('Seeded users:');
  console.log('  admin@demo.com / admin123');
  console.log('  arun|priya|karthik|divya|suresh@demo.com / student123');
  console.log('Referral codes:');
  [admin, ...students].forEach((u) => console.log(`  ${u.name.padEnd(8)} ${u.referralCode}`));
  console.log(`Try: ${process.env.CLIENT_URL}/signup?ref=${arun.referralCode}`);
  process.exit(0);
};

run().catch((err) => {
  console.error('Seed failed:', err.message);
  process.exit(1);
});
